name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update

        # SCSS
        sudo apt-get install sassc

        # Python Lint
        sudo apt-get install pylint3

        # Man
        sudo apt-get install scdoc

        # Build System
        sudo apt-get install meson

        # Debian Packaging
        sudo apt-get install debhelper devscripts

        # Locales
        sudo apt-get install gettext intltool

        # Backend: OpenRazer
        sudo add-apt-repository ppa:openrazer/daily
        sudo apt-get install python3-openrazer

        # Application Dependencies
        sudo apt-get install python3-colorama python3-colour python3-requests python3-setproctitle imagemagick
        sudo apt-get install gir1.2-gtk-3.0 gir1.2-appindicator3-0.1
        sudo apt-get install python3-pyqt5 python3-pyqt5.qtsvg python3-pyqt5.qtwebengine

    - name: Validate JSON
      run: |
        ./scripts/validate-json.py

    - name: Validate SCSS
      run: |
        ./scripts/validate-scss.sh

    - name: Validate Python
      run: |
        ./scripts/validate-py.sh

    - name: Validate Manual
      run: |
        ./scripts/validate-scdoc.sh

    - name: Test Meson and Ninja
      run: |
        meson build --prefix=/tmp/pkg/
        ninja -C build install

    - name: Generate Locales
      run: |
        ./scripts/create-locales.sh

    - name: Build Locales
      run: |
        ./scripts/build-locales.sh

    - name: Create Artifact
      run: |
        ./scripts/create-files-for-opt.sh /tmp/dist

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: polychromatic-run${{github.run_number}}
        path: /tmp/dist/

    - name: Test Debian Packaging
      run: |
        git clean -df
        git checkout .
        sed -i "s/focal/UNRELEASED/g" debian/changelog
        dpkg-buildpackage -S -us -uc -d
        lintian --no-tag-display-limit
        debuild -b

    - name: Prepare GPG Signing Key
      if: ${{ github.event_name == 'push' && github.repository == 'polychromatic/polychromatic' && github.ref == 'refs/heads/master' }}
      run: |
        mkdir -p ~/.gnupg/
        chmod 700 ~/.gnupg
        printf "$BOT_GPG_KEY_BASE64" | base64 --decode > ~/.gnupg/private.key
        gpg --import ~/.gnupg/private.key
      env:
        BOT_GPG_KEY_BASE64: ${{ secrets.BOT_GPG_KEY_BASE64 }}

    - name: Upload Packages to Launchpad
      if: ${{ github.event_name == 'push' && github.repository == 'polychromatic/polychromatic' && github.ref == 'refs/heads/master' }}
      run: |
        git fetch --unshallow --tags
        ./scripts/packaging/prepare-edge-ppa.sh ./

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update

        # Build Dependencies
        sudo apt-get install gettext sassc

        # Application Dependencies
        sudo apt-get install python3-colorama python3-colour python3-requests python3-setproctitle imagemagick
        sudo apt-get install gir1.2-gtk-3.0 gir1.2-appindicator3-0.1
        sudo apt-get install python3-pyqt5 python3-pyqt5.qtsvg python3-pyqt5.qtwebengine

    - name: Install OpenRazer Backend
      run: |
        git clone https://github.com/lah7/openrazer -b sysfs-daemon-test --depth 1 "$GITHUB_WORKSPACE/openrazer"
        sudo apt-get install debhelper dh-python dkms python3-setuptools
        cd openrazer
        ./scripts/build_debs.sh
        sudo apt install ./dist/*.deb
        sudo apt-get install dbus-x11

    - name: Development Build
      run: |
        ./scripts/build-styles.sh
        ./scripts/build-locales.sh

    - name: Test Polychromatic
      run: |
        ./tests/run.sh --verbose

    - name: Test OpenRazer Backend
      run: |
        eval $(sudo dbus-launch --sh-syntax)
        sudo -E ./tests/openrazer/run_daemon.sh "$GITHUB_WORKSPACE/openrazer"
